services:
  python:
    build: 
      context: .
    container_name: python_container
    networks:
      - bot-net
    restart: unless-stopped
    image: pasaashim/tele-bot
  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - bot-net
    restart: unless-stopped
    
networks:
  bot-net:
volumes:
  redis-data:
